import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import StoreProvider from "../providers/StoreProvider";
import { SessionProvider } from "next-auth/react";
import NextAuthSessionProvider from "@/providers/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body data-theme="bumblebee" className="">
        <StoreProvider>
          <NextAuthSessionProvider>
            <Navbar />
            {children}
          </NextAuthSessionProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
